// Static build: content/*.md → public/articles/*.html, homepage pub-list, feed.xml
// Front-matter keys: title, date (YYYY-MM-DD), type (article|talk), description,
// lede (articles), venue (talks), url (external link for talks / offsite articles).
import { readFileSync, writeFileSync, readdirSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { marked } from "marked";

const SITE = "https://jpsmoreira.com";
const ROOT = new URL(".", import.meta.url).pathname;
const CONTENT = join(ROOT, "content");
const PUBLIC = join(ROOT, "public");

const esc = (s) =>
  s.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");

const fill = (tpl, vars) =>
  Object.entries(vars).reduce((out, [k, v]) => out.split(`{{${k}}}`).join(v), tpl);

function parseFrontMatter(raw, file) {
  const m = raw.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
  if (!m) throw new Error(`${file}: missing front-matter`);
  const meta = {};
  for (const line of m[1].split("\n")) {
    const i = line.indexOf(":");
    if (i > 0) meta[line.slice(0, i).trim()] = line.slice(i + 1).trim();
  }
  for (const key of ["title", "date", "type"])
    if (!meta[key]) throw new Error(`${file}: front-matter missing "${key}"`);
  return { meta, body: m[2] };
}

const humanDate = (iso) =>
  new Date(`${iso}T00:00:00Z`).toLocaleDateString("en-US", {
    year: "numeric", month: "long", day: "numeric", timeZone: "UTC",
  });

// ---- Load content ----
const template = readFileSync(join(ROOT, "templates", "article.html"), "utf8");
const entries = readdirSync(CONTENT)
  .filter((f) => f.endsWith(".md"))
  .map((f) => {
    const { meta, body } = parseFrontMatter(readFileSync(join(CONTENT, f), "utf8"), f);
    return { slug: f.replace(/\.md$/, ""), meta, body };
  })
  .sort((a, b) => b.meta.date.localeCompare(a.meta.date));

// ---- Article pages ----
mkdirSync(join(PUBLIC, "articles"), { recursive: true });
for (const e of entries) {
  if (e.meta.url || !e.body.trim()) continue; // external / listing-only entries have no page
  const html = fill(template, {
    TYPE_CLASS: e.meta.type === "talk" ? "talk" : "article",
    TYPE_LABEL: e.meta.type === "talk" ? "Talk" : "Article",
    TITLE: esc(e.meta.title),
    DESCRIPTION: esc(e.meta.description ?? ""),
    LEDE: esc(e.meta.lede ?? e.meta.description ?? ""),
    SLUG: e.slug,
    DATE_HUMAN: humanDate(e.meta.date),
    CONTENT: marked.parse(e.body).trimEnd(),
  });
  writeFileSync(join(PUBLIC, "articles", `${e.slug}.html`), html);
  console.log(`built articles/${e.slug}.html`);
}

// ---- Homepage list (between pub-list markers) ----
const items = entries
  .map((e) => {
    const isTalk = e.meta.type === "talk";
    const href = e.meta.url ?? `/articles/${e.slug}`;
    const external = e.meta.url ? ` target="_blank" rel="noopener"` : "";
    const sub = esc(isTalk ? e.meta.venue ?? "" : e.meta.description ?? "");
    return [
      `        <li class="pub-item">`,
      `          <span class="pub-date mono">${e.meta.date.slice(0, 4)}</span>`,
      `          <div class="pub-body">`,
      `            <span class="pub-tag pub-tag-${isTalk ? "talk" : "article"} mono">${isTalk ? "Talk" : "Article"}</span>`,
      `            <h3><a href="${href}"${external}>${esc(e.meta.title)}</a></h3>`,
      `            <p class="muted">${sub}</p>`,
      `          </div>`,
      `        </li>`,
    ].join("\n");
  })
  .join("\n");

const indexPath = join(PUBLIC, "index.html");
const index = readFileSync(indexPath, "utf8");
const START = "<!-- pub-list:start (generated by build.mjs — edit content/*.md instead) -->";
const END = "<!-- pub-list:end -->";
const s = index.indexOf(START);
const t = index.indexOf(END);
if (s === -1 || t === -1) throw new Error("index.html: pub-list markers not found");
writeFileSync(indexPath, index.slice(0, s + START.length) + "\n" + items + "\n        " + index.slice(t));
console.log(`updated index.html pub-list (${entries.length} entries)`);

// ---- RSS feed (articles with pages only) ----
const feedItems = entries
  .filter((e) => !e.meta.url && e.body.trim() && e.meta.type === "article")
  .map((e) => `    <item>
      <title>${esc(e.meta.title)}</title>
      <link>${SITE}/articles/${e.slug}</link>
      <guid>${SITE}/articles/${e.slug}</guid>
      <pubDate>${new Date(`${e.meta.date}T00:00:00Z`).toUTCString()}</pubDate>
      <description>${esc(e.meta.description ?? "")}</description>
    </item>`)
  .join("\n");

writeFileSync(join(PUBLIC, "feed.xml"), `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
  <channel>
    <title>João Moreira — Articles</title>
    <link>${SITE}</link>
    <description>Articles by João Moreira on developer experience, MES, and software engineering.</description>
    <language>en</language>
${feedItems}
  </channel>
</rss>
`);
console.log("built feed.xml");
